site_name: SnippetLibrary
site_url: https://datec24-DevKRS.github.io/snippet-lb-doc

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md 
    - Configuration: getting-started/configuration.md
    - Development: getting-started/development.md
  - Architecture:
    - Overview: architecture/overview.md
    - Frontend:
      - Structure: architecture/frontend/structure.md
      - Components: architecture/frontend/components.md
      - Services: architecture/frontend/services.md
    - Backend:
      - Structure: architecture/backend/structure.md
      - Database: architecture/backend/database.md
      - Routes: architecture/backend/routes.md
  - Features:
    - Snippets:
      - Creation: features/snippets/creation.md
      - Management: features/snippets/management.md
      - Sharing: features/snippets/sharing.md
    - Folders: features/folders.md
    - Search: features/search.md
  - Deployment:
    - Build: deployment/build.md
    - Firebase: deployment/firebase.md
    - FastAPI: deployment/fastapi.md
  - API:
    - Reference: api/reference.md

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github

repo_name: datec24-DevKRS/SnippetLibrary
repo_url: https://github.com/datec24-DevKRS/SnippetLibrary

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition

plugins:
  - search
